[build]
  functions = "functions"  # Correct path to your functions folder
  publish = "public"  # For static frontend assets (if applicable)

[functions]
  external_node_modules = ["express"]  # Include Express in the bundle
  node_bundler = "esbuild"  # Use esbuild for bundling functions
  memory = 512
  timeout = 10 # increase timeout to 10 seconds
